### ISSUE TITLE
Command Confusion

### ISSUE THREAD

**Issue by ANormalRaft** [PssbleTrngle/DataTrades#8]
### What happened?

1.19.2
Forge 43.2.23

I am confused about the utility of the /villagers refresh command. I assumed that it was a command that you could execute so that you could reload the current villagers with the changes you made to the json files while the game was open akin to the /reload command for datapacks and other useful tools, but while managing the datapack through the paxi mod and also through the world datapack folder, each time I wanted to update the villagers I had to exit out of the game completely and then I'd come back:
 
1-Through paxi, I had to use the command to apply the changes (even though this was a new instance of the game)

2-Through the world datapack, I didn't even need to use the command and the changes were already applied, so it got me wondering about the usefulness of the command

So, is this a bug in the sense that the command is supposed to work while the game is open like /reload? Or maybe this is intended (in which case, a clarification on the mod page would be appreciated)?

### Loader

forge

### Mod Version

1.1.0

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
No, this command is not meant to work like `/reload`, it is only meant to replace all villager's trades with new ones and would also work even if there are no villager trades defined using a datapack.
For now it was only meant for me to be used during development, I will probably add an option to filter/target specific villagers only using the command, to make it more useful.
What it will never do though is reload the datapacks. You have to leave/rejoin the world because the villager trade events are only then executed by forge.
